name: Java CI with Gradle

on: [push, pull_request]

jobs:
  checkstyle:
    name: 🧹 Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK 21 with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - run: chmod +x ./gradlew

      - name: Code Style Check
        run: ./gradlew checkstyleMain --no-daemon

  build:
    name: 🛠️ Build & Test
    needs: checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup JDK 21 with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - run: chmod +x ./gradlew

      - name: Build & Test
        run: ./gradlew build -D spring.profiles.active=test --no-daemon